# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0004_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
    ]
