# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-08 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloword', '0005_auto_20161208_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'admin')], default=1),
        ),
    ]
